In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('data/registration_contacts.csv')
df.head()

,RegistrationContactID,RegistrationID,Type,ContactDescription,CorporationName,Title,FirstName,MiddleInitial,LastName,BusinessHouseNumber,BusinessStreetName,BusinessApartment,BusinessCity,BusinessState,BusinessZip
0,14136004,141360,Agent,CORP,NEW YORK UNIVERSITY,NaN,SCOTT,NaN,LUBLIN,1,PARK AVEUE,5-893,New York,NY,10016
1,10595903,105959,CorporateOwner,CORP,TRUSTEES OF COLUMBIA UNIVERSITY,NaN,NaN,NaN,NaN,400,WEST 119TH STREET,NaN,NEW YORK,NY,10027
2,14084503,140845,CorporateOwner,CORP,TRUSTEES OF COLUMBIA UNIVERSITY,NaN,NaN,NaN,NaN,400,WEST 119TH STREET,NaN,NEW YORK,NY,10027
3,10291103,102911,CorporateOwner,CORP,TRUSTEES OF COLUMBIA UNIVERSITY,NaN,NaN,NaN,NaN,400,WEST 119TH STREET,NaN,NEW YORK,NY,10027
4,12420603,124206,CorporateOwner,CORP,TRUSTEES OF COLUMBIA UNIVERSITY,NaN,NaN,NaN,NaN,400,WEST 119TH STREET,NaN,NEW YORK,NY,10027

In [10]:
registration_ids = df['RegistrationID'].unique().tolist()
registration_ids[0:5]

[141360, 105959, 140845, 102911, 124206]

In [11]:
df_mdf = pd.read_csv('data/multiple_dwelling_registrations_all.csv')
df_mdf.head()

,RegistrationID,BuildingID,BoroID,Boro,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,Zip,Block,Lot,BIN,CommunityBoard,LastRegistrationDate,RegistrationEndDate
0,825850,271859,3,BROOKLYN,787,787,787,EAST 56 STREET,37280,11234.0,7974,28,3223251.0,18,03/19/2026,09/01/2026
1,131572,169,1,MANHATTAN,141,141,141,1 AVENUE,10010,10003.0,450,31,1006381.0,3,08/13/2025,09/01/2026
2,109808,245,1,MANHATTAN,1576,1576,1576,1 AVENUE,10010,10028.0,1561,45,1050399.0,8,08/08/2025,09/01/2026
3,420463,810843,4,QUEENS,163-15,163-15,163-19,130 AVENUE,21870,11434.0,12495,2,4436357.0,12,03/31/2026,09/01/2026
4,335058,383549,3,BROOKLYN,220,220,220,UNION STREET,86530,11231.0,344,22,3004524.0,6,03/30/2026,09/01/2026

In [12]:
df_mdf_filtered = df_mdf[df_mdf['RegistrationID'].isin(registration_ids)].reset_index(drop=True)

In [13]:
df_mdf_filtered.head()

,RegistrationID,BuildingID,BoroID,Boro,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,Zip,Block,Lot,BIN,CommunityBoard,LastRegistrationDate,RegistrationEndDate
0,139611,12578,1,MANHATTAN,330,320,330,EAST 22 STREET,17430,10010.0,927,38,1020564.0,6,03/10/2026,09/01/2026
1,140777,12777,1,MANHATTAN,334,332,336,EAST 26 STREET,17510,10010.0,931,21,1020607.0,6,03/10/2026,09/01/2026
2,142610,864767,1,MANHATTAN,564,562,566,1 AVENUE,10010,10016.0,962,7501,1085695.0,6,03/10/2026,09/01/2026
3,138973,556,1,MANHATTAN,301,297,303,1 AVENUE,10010,10003.0,93,7501,1020438.0,6,02/02/2024,09/30/2024
4,611029,38087,1,MANHATTAN,546,546,546,WEST 113 STREET,36030,10025.0,1884,53,1057008.0,9,10/05/2024,09/01/2025

In [14]:
df_merged = pd.merge(df_mdf_filtered, df, on='RegistrationID', how='left')
pd.set_option('display.max_columns', 30)
df_merged.head()

,RegistrationID,BuildingID,BoroID,Boro,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,Zip,Block,Lot,BIN,CommunityBoard,LastRegistrationDate,RegistrationEndDate,RegistrationContactID,Type,ContactDescription,CorporationName,Title,FirstName,MiddleInitial,LastName,BusinessHouseNumber,BusinessStreetName,BusinessApartment,BusinessCity,BusinessState,BusinessZip
0,139611,12578,1,MANHATTAN,330,320,330,EAST 22 STREET,17430,10010.0,927,38,1020564.0,6,03/10/2026,09/01/2026,13961103,CorporateOwner,CORP,NEW YORK UNIVERSITY,NaN,NaN,NaN,NaN,339,EAST 28TH STRRET,NaN,New York,NY,10016
1,139611,12578,1,MANHATTAN,330,320,330,EAST 22 STREET,17430,10010.0,927,38,1020564.0,6,03/10/2026,09/01/2026,13961104,Agent,CORP,NEW YORK UNIVERSITY,NaN,SCOTT,NaN,LUBLIN,1,PARK AVEUE,5-893,New York,NY,10016
2,140777,12777,1,MANHATTAN,334,332,336,EAST 26 STREET,17510,10010.0,931,21,1020607.0,6,03/10/2026,09/01/2026,14077704,Agent,CORP,NEW YORK UNIVERSITY,NaN,SCOTT,NaN,LUBLIN,1,PARK AVEUE,5-893,New York,NY,10016
3,140777,12777,1,MANHATTAN,334,332,336,EAST 26 STREET,17510,10010.0,931,21,1020607.0,6,03/10/2026,09/01/2026,14077703,CorporateOwner,CORP,NEW YORK UNIVERSITY,NaN,NaN,NaN,NaN,339,EAST 28TH STREET,NaN,New York,NY,10016
4,142610,864767,1,MANHATTAN,564,562,566,1 AVENUE,10010,10016.0,962,7501,1085695.0,6,03/10/2026,09/01/2026,14261004,Agent,CORP,NEW YORK UNIVERSITY,NaN,SCOTT,NaN,LUBLIN,1,PARK AVEUE,5-893,New York,NY,10016

In [15]:
df_merged.shape

(298, 30)

In [16]:
df_clean = df_merged[['RegistrationID', 'BuildingID', 'Boro', 'BoroID', 'HouseNumber', 'StreetName', 'Zip', 'Block', 'Lot', 'BIN', 'RegistrationContactID', 'CorporationName', 'BusinessHouseNumber', 'BusinessStreetName', 'BusinessApartment', 'BusinessCity', 'BusinessState', 'BusinessZip']]
df_clean.shape

(298, 18)

In [17]:
df_clean['house_num_string'] = df_clean['HouseNumber'].copy().astype('str')
df_clean['zip_int'] = df_clean['Zip'].copy().astype('int')
df_clean['zip_string'] = df_clean['zip_int'].copy().astype('str')

/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/189480308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['house_num_string'] = df_clean['HouseNumber'].copy().astype('str')
/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/189480308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['zip_int'] = df_clean['Zip'].copy().astype('int')
/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/189480308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['zip_string'] = df_clean['zip_int'].copy().astype('str')

In [18]:
df_clean.dtypes

RegistrationID             int64
BuildingID                 int64
Boro                      object
BoroID                     int64
HouseNumber               object
StreetName                object
Zip                      float64
Block                      int64
Lot                        int64
BIN                      float64
RegistrationContactID      int64
CorporationName           object
BusinessHouseNumber       object
BusinessStreetName        object
BusinessApartment         object
BusinessCity              object
BusinessState             object
BusinessZip                int64
house_num_string          object
zip_int                    int64
zip_string                object
dtype: object

In [19]:
df_clean['building_address'] = df_clean['house_num_string'] + " " + df_clean['StreetName'] + ", NEW YORK, NY, " + df_clean['zip_string']
df_clean.head()

/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/2104591313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['building_address'] = df_clean['house_num_string'] + " " + df_clean['StreetName'] + ", NEW YORK, NY, " + df_clean['zip_string']

,RegistrationID,BuildingID,Boro,BoroID,HouseNumber,StreetName,Zip,Block,Lot,BIN,RegistrationContactID,CorporationName,BusinessHouseNumber,BusinessStreetName,BusinessApartment,BusinessCity,BusinessState,BusinessZip,house_num_string,zip_int,zip_string,building_address
0,139611,12578,MANHATTAN,1,330,EAST 22 STREET,10010.0,927,38,1020564.0,13961103,NEW YORK UNIVERSITY,339,EAST 28TH STRRET,NaN,New York,NY,10016,330,10010,10010,"330 EAST 22 STREET, NEW YORK, NY, 10010"
1,139611,12578,MANHATTAN,1,330,EAST 22 STREET,10010.0,927,38,1020564.0,13961104,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,330,10010,10010,"330 EAST 22 STREET, NEW YORK, NY, 10010"
2,140777,12777,MANHATTAN,1,334,EAST 26 STREET,10010.0,931,21,1020607.0,14077704,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,334,10010,10010,"334 EAST 26 STREET, NEW YORK, NY, 10010"
3,140777,12777,MANHATTAN,1,334,EAST 26 STREET,10010.0,931,21,1020607.0,14077703,NEW YORK UNIVERSITY,339,EAST 28TH STREET,NaN,New York,NY,10016,334,10010,10010,"334 EAST 26 STREET, NEW YORK, NY, 10010"
4,142610,864767,MANHATTAN,1,564,1 AVENUE,10016.0,962,7501,1085695.0,14261004,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,564,10016,10016,"564 1 AVENUE, NEW YORK, NY, 10016"

In [20]:
df_clean['business_house_num_string'] = df_clean['BusinessHouseNumber'].copy().astype('str')
df_clean['business_zip_int'] = df_clean['BusinessZip'].copy().astype('int')
df_clean['business_zip_string'] = df_clean['business_zip_int'].copy().astype('str')

/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/2253773216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['business_house_num_string'] = df_clean['BusinessHouseNumber'].copy().astype('str')
/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/2253773216.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['business_zip_int'] = df_clean['BusinessZip'].copy().astype('int')
/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/2253773216.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['business_zip_string'] = df_clean['business_zip_int'].copy().astype('str')

In [21]:
has_apt = df_clean['BusinessApartment'].notna()

# 2. Build the full address using a conditional format
df_clean['business_address'] = (
    df_clean['business_house_num_string'] + ' '
    + df_clean['BusinessStreetName'] +
    np.where(has_apt, ' APARTMENT ' + df_clean['BusinessApartment'], '') + ', '
    + df_clean['BusinessCity'] + ', '
    + df_clean['BusinessState'] + ' '
    + df_clean['business_zip_string']
)

df_clean['business_address']

/var/folders/0c/3z452hlj1pzb2yr_79hcgh8r0000gn/T/ipykernel_87217/3648303383.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['business_address'] = (

0              339 EAST 28TH STRRET, New York, NY 10016
1      1 PARK AVEUE APARTMENT 5-893, New York, NY 10016
2      1 PARK AVEUE APARTMENT 5-893, New York, NY 10016
3              339 EAST 28TH STREET, New York, NY 10016
4      1 PARK AVEUE APARTMENT 5-893, New York, NY 10016
                             ...
293           400 WEST 119TH STREET, NEW YORK, NY 10027
294           400 WEST 119TH STREET, NEW YORK, NY 10027
295           400 WEST 119TH STREET, NEW YORK, NY 10027
296           400 WEST 119TH STREET, NEW YORK, NY 10027
297           400 WEST 119TH STREET, New York, NY 10027
Name: business_address, Length: 298, dtype: object

In [22]:
df_clean.head()

,RegistrationID,BuildingID,Boro,BoroID,HouseNumber,StreetName,Zip,Block,Lot,BIN,RegistrationContactID,CorporationName,BusinessHouseNumber,BusinessStreetName,BusinessApartment,BusinessCity,BusinessState,BusinessZip,house_num_string,zip_int,zip_string,building_address,business_house_num_string,business_zip_int,business_zip_string,business_address
0,139611,12578,MANHATTAN,1,330,EAST 22 STREET,10010.0,927,38,1020564.0,13961103,NEW YORK UNIVERSITY,339,EAST 28TH STRRET,NaN,New York,NY,10016,330,10010,10010,"330 EAST 22 STREET, NEW YORK, NY, 10010",339,10016,10016,"339 EAST 28TH STRRET, New York, NY 10016"
1,139611,12578,MANHATTAN,1,330,EAST 22 STREET,10010.0,927,38,1020564.0,13961104,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,330,10010,10010,"330 EAST 22 STREET, NEW YORK, NY, 10010",1,10016,10016,"1 PARK AVEUE APARTMENT 5-893, New York, NY 10016"
2,140777,12777,MANHATTAN,1,334,EAST 26 STREET,10010.0,931,21,1020607.0,14077704,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,334,10010,10010,"334 EAST 26 STREET, NEW YORK, NY, 10010",1,10016,10016,"1 PARK AVEUE APARTMENT 5-893, New York, NY 10016"
3,140777,12777,MANHATTAN,1,334,EAST 26 STREET,10010.0,931,21,1020607.0,14077703,NEW YORK UNIVERSITY,339,EAST 28TH STREET,NaN,New York,NY,10016,334,10010,10010,"334 EAST 26 STREET, NEW YORK, NY, 10010",339,10016,10016,"339 EAST 28TH STREET, New York, NY 10016"
4,142610,864767,MANHATTAN,1,564,1 AVENUE,10016.0,962,7501,1085695.0,14261004,NEW YORK UNIVERSITY,1,PARK AVEUE,5-893,New York,NY,10016,564,10016,10016,"564 1 AVENUE, NEW YORK, NY, 10016",1,10016,10016,"1 PARK AVEUE APARTMENT 5-893, New York, NY 10016"

In [25]:
df_final = df_clean[['CorporationName', 'building_address', 'business_address', 'RegistrationID', 'BuildingID', 'Boro', 'BoroID', 'Block', 'Lot', 'BIN', 'RegistrationContactID']]

In [26]:
df_final.to_csv('data/pt_1.csv', index=False)