In [2]:
import pandas as pd
import duckdb

In [3]:
df_pt_1 = pd.read_csv('data/pt_1.csv')
df_pt_1.columns

Index(['CorporationName', 'building_address', 'business_address',
       'RegistrationID', 'BuildingID', 'Boro', 'BoroID', 'Block', 'Lot', 'BIN',
       'RegistrationContactID'],
      dtype='object')

In [4]:
query = '''
SELECT *
FROM df_pt_1 AS df
LEFT JOIN read_csv_auto('data/real_property_legals.csv') AS legals
ON df."BoroID" = legals."BOROUGH"
AND df."Block" = legals."BLOCK"
AND df."Lot" = legals."LOT";
'''

df_legals = duckdb.sql(query).df()
df_legals.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,BoroID,Block,Lot,BIN,...,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE
0,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,1,461,6,1090311.0,...,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-08-31
1,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,1,461,6,1090311.0,...,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-08-31
2,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,1,461,6,1090311.0,...,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-08-31
3,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,1,461,6,1090311.0,...,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-08-31
4,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,1,461,6,1090311.0,...,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-08-31

In [5]:
df_legals.columns

Index(['CorporationName', 'building_address', 'business_address',
       'RegistrationID', 'BuildingID', 'Boro', 'BoroID', 'Block', 'Lot', 'BIN',
       'RegistrationContactID', 'DOCUMENT ID', 'RECORD TYPE', 'BOROUGH',
       'BLOCK_1', 'LOT_1', 'EASEMENT', 'PARTIAL LOT', 'AIR RIGHTS',
       'SUBTERRANEAN RIGHTS', 'PROPERTY TYPE', 'STREET NUMBER', 'STREET NAME',
       'UNIT', 'GOOD THROUGH DATE'],
      dtype='object')

In [6]:
query = '''
SELECT *
FROM df_legals AS df
LEFT JOIN read_csv_auto('data/real_property_master.csv') AS master
ON df."DOCUMENT ID" = master."DOCUMENT ID";
'''

df_legals_master = duckdb.sql(query).df()
df_legals_master.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,BoroID,Block,Lot,BIN,...,DOC. TYPE,DOC. DATE,DOC. AMOUNT,RECORDED / FILED,MODIFIED DATE,REEL YEAR,REEL NBR,REEL PAGE,% TRANSFERRED,GOOD THROUGH DATE_1
0,TRUSTEES OF COLUMBIA UNIVERSITY,"549 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",128836,38089,MANHATTAN,1,1885,7,1057021.0,...,DEED,NaT,0.0,1977-03-02,2002-07-01,1977,392,1401,0.0,2015-07-31
1,TRUSTEES OF COLUMBIA UNIVERSITY,"612 WEST 114 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, New York, NY 10027",124696,38203,MANHATTAN,1,1895,165,1057364.0,...,DEED,NaT,0.0,1969-01-01,2002-07-01,1969,130,1406,0.0,2015-07-31
2,COLUMBIA UNIVERSITY,"154 WEST 119 STREET, NEW YORK, NY, 10026","215 215 W 95TH ST APARTMENT PHF, NEW YORK CITY...",132091,38678,MANHATTAN,1,1903,157,1057529.0,...,DEED,2007-04-11,1500000.0,2007-05-16,2007-05-16,0,0,0,100.0,2015-07-31
3,NEW YORK UNIVERSITY,"140 EAST 14 STREET, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",141977,829405,MANHATTAN,1,559,22,1085790.0,...,DEED,1990-03-16,0.0,1990-03-22,1990-03-22,1990,1677,1866,0.0,2015-07-31
4,NEW YORK UNIVERSITY,"140 EAST 14 STREET, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, New York, NY ...",141977,829405,MANHATTAN,1,559,22,1085790.0,...,DEED,1990-03-16,0.0,1990-03-22,1990-03-22,1990,1677,1866,0.0,2015-07-31

In [7]:
query = '''
SELECT *
FROM df_legals AS df
LEFT JOIN read_csv_auto('data/real_property_parties.csv') AS parties
ON df."DOCUMENT ID" = parties."DOCUMENT ID";
'''

df_legals_master_parties = duckdb.sql(query).df()
df_legals_master_parties.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,BoroID,Block,Lot,BIN,...,RECORD TYPE_1,PARTY TYPE,NAME,ADDRESS 1,ADDRESS 2,COUNTRY,CITY,STATE,ZIP,GOOD THROUGH DATE_1
0,NEW YORK UNIVERSITY,"787 BROADWAY, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",132439,8543,MANHATTAN,1,562,30,1009112.0,...,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
1,NEW YORK UNIVERSITY,"787 BROADWAY, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",132439,8543,MANHATTAN,1,562,30,1009112.0,...,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
2,NEW YORK UNIVERSITY,"25 UNION SQUARE, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140590,805419,MANHATTAN,1,843,22,1087304.0,...,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
3,NEW YORK UNIVERSITY,"25 UNION SQUARE, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140590,805419,MANHATTAN,1,843,22,1087304.0,...,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
4,NEW YORK UNIVERSITY,"21 EAST 15 STREET, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140569,12128,MANHATTAN,1,843,22,1078700.0,...,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM

In [8]:
pd.set_option('display.max_columns', 70)

df_legals_master_parties.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,BoroID,Block,Lot,BIN,RegistrationContactID,DOCUMENT ID,RECORD TYPE,BOROUGH,BLOCK_1,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE,DOCUMENT ID_1,RECORD TYPE_1,PARTY TYPE,NAME,ADDRESS 1,ADDRESS 2,COUNTRY,CITY,STATE,ZIP,GOOD THROUGH DATE_1
0,NEW YORK UNIVERSITY,"787 BROADWAY, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",132439,8543,MANHATTAN,1,562,30,1009112.0,13243903,2025102200444001,L,1,562,30,N,E,N,N,OT,787,BROADWAY,None,2025-10-31,2025102200444001,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
1,NEW YORK UNIVERSITY,"787 BROADWAY, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",132439,8543,MANHATTAN,1,562,30,1009112.0,13243904,2025102200444001,L,1,562,30,N,E,N,N,OT,787,BROADWAY,None,2025-10-31,2025102200444001,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
2,NEW YORK UNIVERSITY,"25 UNION SQUARE, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140590,805419,MANHATTAN,1,843,22,1087304.0,14059003,2025102200444001,L,1,843,22,N,E,N,N,OT,21-25,UNION SQUARE,None,2025-10-31,2025102200444001,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
3,NEW YORK UNIVERSITY,"25 UNION SQUARE, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140590,805419,MANHATTAN,1,843,22,1087304.0,14059004,2025102200444001,L,1,843,22,N,E,N,N,OT,21-25,UNION SQUARE,None,2025-10-31,2025102200444001,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM
4,NEW YORK UNIVERSITY,"21 EAST 15 STREET, NEW YORK, NY, 10003","10 ASTOR PLACE APARTMENT 7TH FL, NEW YORK, NY ...",140569,12128,MANHATTAN,1,843,22,1078700.0,14056903,2025102200444001,L,1,843,22,N,E,N,N,OT,21-25,UNION SQUARE,None,2025-10-31,2025102200444001,P,1,NYC DEPARTMENT OF TRANSPORTATION,OFFICE OF CITYSCAPE & FRANCHISES,55 WATER ST 9TH FL SW,US,NEW YORK,NY,10041,2025 Oct 31 12:00:00 AM


### End of Step 6: Merged Data
OK, to make this more accessible I am revealing at least my final data frame for the three merged ACRIS tables.

In [9]:
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace(' ', '_')
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace('.', '_')
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace('__', '_')

In [10]:
df_merged_final = df_legals_master_parties.loc[:, ~df_legals_master_parties.columns.duplicated(keep='first')].copy()

In [11]:
df_merged_final.shape

(7508, 36)

In [12]:
df_merged_final['buildingid'].value_counts()

buildingid
2338      530
840219    456
12578     370
29234     254
12128     242
         ...
29243       1
38088       1
38290       1
38192       1
25573       1
Name: count, Length: 238, dtype: int64

In [13]:
df_merged_final['document_id'].nunique()

1399

In [14]:
df_merged_final.to_csv('data/pt_2.csv', index=False)