In [15]:
import pandas as pd
import duckdb

In [16]:
df_pt_1 = pd.read_csv('data/pt_1.csv')
df_pt_1.columns

Index(['CorporationName', 'building_address', 'business_address',
       'RegistrationID', 'BuildingID', 'Boro', 'Block', 'Lot', 'BIN',
       'RegistrationContactID'],
      dtype='object')

In [17]:
query = '''
SELECT *
FROM df_pt_1 AS df
LEFT JOIN read_csv_auto('data/real_property_legals.csv') AS legals
ON df."Block" = legals."BLOCK"
AND df."Lot" = legals."LOT";
'''

df_legals = duckdb.sql(query).df()
df_legals.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,Block,Lot,BIN,RegistrationContactID,DOCUMENT ID,RECORD TYPE,BOROUGH,BLOCK_1,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE
0,NEW YORK UNIVERSITY,"377 EAST 33 STREET, NEW YORK, NY, 10016","399 EAST 28TH STREET, New York, NY 10016",141360,840219,MANHATTAN,939,28,1086501.0,14136003,2024071900852001,L,1,939,28,N,E,N,N,SC,377,E 33RD STREET,15E,2024-07-31
1,NEW YORK UNIVERSITY,"377 EAST 33 STREET, NEW YORK, NY, 10016","1 PARK AVEUE APARTMENT 5-893, New York, NY 10016",141360,840219,MANHATTAN,939,28,1086501.0,14136004,2024071900852001,L,1,939,28,N,E,N,N,SC,377,E 33RD STREET,15E,2024-07-31
2,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,461,6,1090311.0,14398704,2024071600409001,L,1,461,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-07-31
3,New York University,"200 EAST 6 STREET, NEW YORK, NY, 10003","10 Astor Place APARTMENT 7th Fl, New York, NY ...",143987,966428,MANHATTAN,461,6,1090311.0,14398703,2024071600409001,L,1,461,6,N,E,N,N,CR,35,COOPER SQUARE,None,2024-07-31
4,NEW YORK UNIVERSITY,"16 EAST 8 STREET, NEW YORK, NY, 10003","2 WASHINGTON SQ VILLAGE APARTMENT 1T, New York...",107712,11225,MANHATTAN,550,29,1077902.0,10771204,2024052300256004,L,4,550,29,N,E,N,N,AP,30-40,23RD STREET,None,2024-05-31

In [18]:
df_legals.columns

Index(['CorporationName', 'building_address', 'business_address',
       'RegistrationID', 'BuildingID', 'Boro', 'Block', 'Lot', 'BIN',
       'RegistrationContactID', 'DOCUMENT ID', 'RECORD TYPE', 'BOROUGH',
       'BLOCK_1', 'LOT_1', 'EASEMENT', 'PARTIAL LOT', 'AIR RIGHTS',
       'SUBTERRANEAN RIGHTS', 'PROPERTY TYPE', 'STREET NUMBER', 'STREET NAME',
       'UNIT', 'GOOD THROUGH DATE'],
      dtype='object')

In [19]:
query = '''
SELECT *
FROM df_legals AS df
LEFT JOIN read_csv_auto('data/real_property_master.csv') AS master
ON df."DOCUMENT ID" = master."DOCUMENT ID";
'''

df_legals_master = duckdb.sql(query).df()
df_legals_master.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,Block,Lot,BIN,RegistrationContactID,DOCUMENT ID,RECORD TYPE,BOROUGH,BLOCK_1,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE,DOCUMENT ID_1,RECORD TYPE_1,CRFN,BOROUGH_1,DOC. TYPE,DOC. DATE,DOC. AMOUNT,RECORDED / FILED,MODIFIED DATE,REEL YEAR,REEL NBR,REEL PAGE,% TRANSFERRED,GOOD THROUGH DATE_1
0,TRUSTEES OF COLUMBIA UNIVERSITY,"523 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",122672,38074,MANHATTAN,1885,20,1057027.0,12267203,2025052200862001,L,3,1885,20,N,E,N,N,CR,37,FRANKLIN AVENUE,None,2025-05-31,2025052200862001,A,2025000141066,1,DEED,2025-05-21,0.0,2025-05-27,2025-05-27,0,0,0,100.0,2025-05-31
1,TRUSTEES OF COLUMBIA UNIVERSITY,"533 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",107746,38081,MANHATTAN,1885,15,1057023.0,10774603,2025052200862001,L,3,1885,15,N,E,N,N,CR,28,SKILLMAN STREET,None,2025-05-31,2025052200862001,A,2025000141066,1,DEED,2025-05-21,0.0,2025-05-27,2025-05-27,0,0,0,100.0,2025-05-31
2,TRUSTEES OF COLUMBIA UNIVERSITY,"403 WEST 115 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",102909,38275,MANHATTAN,1867,54,1056051.0,10290903,2025030200051001,L,4,1867,54,N,E,N,N,D2,92-23,52ND AVENUE,None,2025-03-31,2025030200051001,A,2025000062056,1,DEED,2025-02-27,0.0,2025-03-05,2025-03-05,0,0,0,50.0,2025-03-31
3,TRUSTEES OF COLUMBIA UNIVERSITY,"415 WEST 118 STREET, NEW YORK, NY, 10027","400 WEST 119TH STREET, NEW YORK, NY 10027",102347,38603,MANHATTAN,1962,11,1059503.0,10234703,2025021900242001,L,4,1962,11,N,E,N,N,D3,108-16,OTIS AVENUE,None,2025-02-28,2025021900242001,A,2025000053073,1,DEED,2024-12-30,0.0,2025-02-26,2025-02-26,0,0,0,100.0,2025-02-28
4,TRUSTEES OF COLUMBIA UNIVERSITY,"452 RIVERSIDE DRIVE, NEW YORK, NY, 10027","400 WEST 119TH STREET, NEW YORK, NY 10027",123848,27291,MANHATTAN,1990,54,1059831.0,12384803,2024123100217001,L,3,1990,54,N,E,N,N,D2,167,PUTNAM AVENUE,None,2025-01-31,2024123100217001,A,2025000000801,1,DEED,2024-12-19,3027500.0,2025-01-02,2025-01-02,0,0,0,100.0,2025-01-31

In [20]:
query = '''
SELECT *
FROM df_legals AS df
LEFT JOIN read_csv_auto('data/real_property_parties.csv') AS parties
ON df."DOCUMENT ID" = parties."DOCUMENT ID";
'''

df_legals_master_parties = duckdb.sql(query).df()
df_legals_master_parties.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,Block,Lot,BIN,RegistrationContactID,DOCUMENT ID,RECORD TYPE,BOROUGH,BLOCK_1,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE,DOCUMENT ID_1,RECORD TYPE_1,PARTY TYPE,NAME,ADDRESS 1,ADDRESS 2,COUNTRY,CITY,STATE,ZIP,GOOD THROUGH DATE_1
0,TRUSTEES OF COLUMBIA UNIVERSITY,"541 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",113540,38084,MANHATTAN,1885,11,1057022.0,11354003,2016041301502003,L,4,1885,11,N,E,N,N,GR,94-30,51ST AVENUE,None,2016-04-30,2016041301502003,P,1,94-28 REALTY INC.,94-28/30 51ST AVENUE,None,US,ELMHURST,NY,11373,2026 Apr 30 12:00:00 AM
1,TRUSTEES OF COLUMBIA UNIVERSITY,"536 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",112206,38082,MANHATTAN,1884,48,1057005.0,11220603,2014031801081014,L,3,1884,48,N,E,N,N,CR,378,FLUSHING AVENUE,None,2015-07-31,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM
2,TRUSTEES OF COLUMBIA UNIVERSITY,"541 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",113540,38084,MANHATTAN,1885,11,1057022.0,11354003,2016041301502003,L,4,1885,11,N,E,N,N,GR,94-30,51ST AVENUE,None,2026-04-30,2016041301502003,P,1,94-28 REALTY INC.,94-28/30 51ST AVENUE,None,US,ELMHURST,NY,11373,2026 Apr 30 12:00:00 AM
3,TRUSTEES OF COLUMBIA UNIVERSITY,"536 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",112206,38082,MANHATTAN,1884,48,1057005.0,11220603,2014031801081014,L,3,1884,48,N,E,N,N,CR,378,FLUSHING AVENUE,None,2026-04-30,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM
4,TRUSTEES OF COLUMBIA UNIVERSITY,"506 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, New York, NY 10027",128724,38068,MANHATTAN,1884,40,1057001.0,12872403,2014031801081014,L,3,1884,40,N,E,N,N,CR,376,FLUSHING AVENUE,None,2026-04-30,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM

In [21]:
pd.set_option('display.max_columns', 70)

df_legals_master_parties.head()

,CorporationName,building_address,business_address,RegistrationID,BuildingID,Boro,Block,Lot,BIN,RegistrationContactID,DOCUMENT ID,RECORD TYPE,BOROUGH,BLOCK_1,LOT_1,EASEMENT,PARTIAL LOT,AIR RIGHTS,SUBTERRANEAN RIGHTS,PROPERTY TYPE,STREET NUMBER,STREET NAME,UNIT,GOOD THROUGH DATE,DOCUMENT ID_1,RECORD TYPE_1,PARTY TYPE,NAME,ADDRESS 1,ADDRESS 2,COUNTRY,CITY,STATE,ZIP,GOOD THROUGH DATE_1
0,TRUSTEES OF COLUMBIA UNIVERSITY,"541 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",113540,38084,MANHATTAN,1885,11,1057022.0,11354003,2016041301502003,L,4,1885,11,N,E,N,N,GR,94-30,51ST AVENUE,None,2016-04-30,2016041301502003,P,1,94-28 REALTY INC.,94-28/30 51ST AVENUE,None,US,ELMHURST,NY,11373,2026 Apr 30 12:00:00 AM
1,TRUSTEES OF COLUMBIA UNIVERSITY,"536 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",112206,38082,MANHATTAN,1884,48,1057005.0,11220603,2014031801081014,L,3,1884,48,N,E,N,N,CR,378,FLUSHING AVENUE,None,2015-07-31,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM
2,TRUSTEES OF COLUMBIA UNIVERSITY,"541 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",113540,38084,MANHATTAN,1885,11,1057022.0,11354003,2016041301502003,L,4,1885,11,N,E,N,N,GR,94-30,51ST AVENUE,None,2026-04-30,2016041301502003,P,1,94-28 REALTY INC.,94-28/30 51ST AVENUE,None,US,ELMHURST,NY,11373,2026 Apr 30 12:00:00 AM
3,TRUSTEES OF COLUMBIA UNIVERSITY,"536 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, NEW YORK, NY 10027",112206,38082,MANHATTAN,1884,48,1057005.0,11220603,2014031801081014,L,3,1884,48,N,E,N,N,CR,378,FLUSHING AVENUE,None,2026-04-30,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM
4,TRUSTEES OF COLUMBIA UNIVERSITY,"506 WEST 113 STREET, NEW YORK, NY, 10025","400 WEST 119TH STREET, New York, NY 10027",128724,38068,MANHATTAN,1884,40,1057001.0,12872403,2014031801081014,L,3,1884,40,N,E,N,N,CR,376,FLUSHING AVENUE,None,2026-04-30,2014031801081014,P,2,LOTUS RESIDENCES LLC,266 BROADWAY,SUITE 301,US,BROOKLYN,NY,11211,2026 Apr 30 12:00:00 AM


### End of Step 6: Merged Data
OK, to make this more accessible I am revealing at least my final data frame for the three merged ACRIS tables.

In [22]:
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace(' ', '_')
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace('.', '_')
df_legals_master_parties.columns = df_legals_master_parties.columns.str.lower().str.replace('__', '_')

In [23]:
df_merged_final = df_legals_master_parties.loc[:, ~df_legals_master_parties.columns.duplicated(keep='first')].copy()

In [24]:
df_merged_final.shape

(20807, 35)

In [25]:
df_merged_final['buildingid'].value_counts()

buildingid
840219    600
2338      562
34449     464
29181     452
38068     419
         ...
38091       1
38088       1
5513        1
38093       1
38182       1
Name: count, Length: 238, dtype: int64

In [26]:
df_merged_final['document_id'].nunique()

4709

In [27]:
df_merged_final.to_csv('data/pt_2.csv', index=False)